{{- if .Values.config.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data: {{ .Values.config.data | toYaml | nindent 2 }}
{{ end }}