{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  podSelector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}

  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
    {{- with .Values.networkPolicy.egress.rules}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if and .Values.networkPolicy.ingress.enabled .Values.networkPolicy.ingress.rules }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress.rules | nindent 4 }}
  {{- end }}
{{- end }}
