---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: app
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    {{- with .Values.service.extraPorts }}
      {{- toYaml . | nindent 4 }}
    {{- end}}
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
