---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
