{{- if .Values.tcpRoute -}}
{{- $fullName := include "generic.fullname" . -}}
{{- range $port, $values := .Values.tcpRoute }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ $fullName }}-{{ $port }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
  {{- with $values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ $values.parentRefs.name }}
      namespace: {{ $values.parentRefs.namespace | default $.Release.Namespace }}
      port: {{ $port }}
  rules:
    - backendRefs:
      - name: {{ $fullName }}
        port: {{ $port }}
{{- end }}
{{- end }}
